version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: geo_ip:${GEO_IP_VERSION:-latest}
    restart: always
    expose:
    - "8000"
    deploy:
      replicas: 2
    env_file:
    - .env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      GEO_IP_HOST: 0.0.0.0

  redis:
    image: bitnami/redis:6.2.5
    hostname: "geo_ip-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
    - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  nginx:
    image: nginx:latest
    volumes:
    - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - api
    ports:
    - "4001:4001"

networks:
  default:
    driver: bridge
    name: api
